# Pre-commit hooks for HUSAI project
# Install with: pre-commit install
# Run manually with: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Prevent files >1MB
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=100',
          '--extend-ignore=E203,W503',  # Black compatibility
          '--max-complexity=15'
        ]
        additional_dependencies: [
          flake8-docstrings,
          flake8-bugbear,
          flake8-comprehensions
        ]

  # Type checking (optional - can be slow)
  # Uncomment if you want strict type checking on every commit
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.18.2
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]
  #       args: ['--ignore-missing-imports', '--strict']

  # Notebook cleaning (remove outputs)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.2
    hooks:
      - id: nbstripout
        args: ['--extra-keys', 'metadata.kernelspec metadata.language_info']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
        exclude: ^tests/

# Configuration for specific hooks can go in pyproject.toml
