name: husai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version - 3.11 for maximum compatibility
  - python=3.11

  # PyTorch with CUDA 11.8 (avoid PyTorch 2.6.0 breaking changes)
  # For CUDA 12.1, change pytorch-cuda=11.8 to pytorch-cuda=12.1
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8

  # System utilities
  - pip
  - git

  # Install remaining dependencies via pip
  - pip:
    # ===================
    # Core Deep Learning
    # ===================
    - transformers==4.57.1
    - datasets==4.3.0
    - accelerate==1.11.0

    # ================================
    # Mechanistic Interpretability
    # ================================
    - transformer-lens==2.16.1
    - sae-lens==6.17.0
    - einops==0.8.1
    - jaxtyping==0.3.1
    - circuitsvis==1.43.3  # Visualization library
    - nnsight==0.5.9       # Alternative for large models

    # ====================
    # Experiment Tracking
    # ====================
    - wandb==0.22.2
    - tensorboard==2.20.0

    # ====================
    # Scientific Computing
    # ====================
    - numpy==2.3.4
    - scipy==1.16.2
    - pandas==2.3.3
    - scikit-learn==1.7.2
    - umap-learn==0.5.9.post2

    # ==============
    # Visualization
    # ==============
    - matplotlib==3.10.7
    - seaborn==0.13.2
    - plotly==6.3.1

    # ==================
    # Development Tools
    # ==================
    - pytest==8.4.2
    - pytest-cov==7.0.0
    - black==25.9.0
    - isort==7.0.0
    - flake8==7.3.0
    - mypy==1.18.2
    - pre-commit==4.3.0

    # =======
    # Jupyter
    # =======
    - jupyterlab==4.4.10
    - ipykernel==7.0.1

    # =========
    # Utilities
    # =========
    - tqdm  # Progress bars
    - rich  # Beautiful terminal output
